[   {   'description': 'A reserved IP scope for system',
        'id': 1L,
        'ip_scope_name': 'SYS_IP_SCOPE'},
    {   'description': 'Networks in Legacy Tekelec Lab',
        'id': 2L,
        'ip_scope_name': 'Tekelec'},
    {   'description': 'Backplane Networks in Legacy Tekelec Lab',
        'id': 3L,
        'ip_scope_name': 'Tekelec Backplane'},
    {   'description': 'Networks of Physical Machine in Oracle Lab',
        'id': 4L,
        'ip_scope_name': 'Oracle Lab IP'},
    {   'description': 'Networks of Virtual Machine for QP Team',
        'id': 5L,
        'ip_scope_name': 'QP VM IP'},
    {   'description': 'Networks of Virtual Machine for APP Team',
        'id': 6L,
        'ip_scope_name': 'APP VM IP'},
    {   'description': 'Networks of Virtual Machine for PV Team',
        'id': 7L,
        'ip_scope_name': 'PV VM IP'},
    {   'description': 'Networks of Virtual Machine for CMP Team',
        'id': 8L,
        'ip_scope_name': 'CMP VM IP'},
    {   'description': 'Virtual Backplane Networks 01 for QP Team',
        'id': 9L,
        'ip_scope_name': 'QP VM BP IP 01'}]