CREATE DATABASE IF NOT EXISTS `web`;
USE `web`;
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `ID`       INT(8) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) DEFAULT NULL,
  `password` VARCHAR(16) DEFAULT NULL,
  `email`    VARCHAR(32) DEFAULT NULL,
  PRIMARY KEY (`ID`)
)
  ENGINE =InnoDB
  DEFAULT CHARSET =UTF8;